# yaml(*.yml)
#     yet another markup language
#     가벼운 마크업 언어로 사용
#
# 기본 문법
#   # 는 주석
#   기본표현
#      key: value     <- : 다음에는 반드시 공백문자가 와야 함
#
#   key:
#       key_1:
#           key_2:
#               key_3:
#                   ..

# 서버포트 번호
server:
  port: 80
  tomcat:
    max-http-form-post-size: 10GB

spring:
  application:
    name: KBoard

  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  # datasource 설정. MySql등 spring-jdbc 사용시 아래 정보 없으면 서버가동 에러.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval
    username: ${rds.username}
    password: ${rds.password}

  # security
  security:
    user:
      name: myappuser
      password: myapp1234


  servlet:
    # Multipart request 의 업로드 파일 크기 제한 설정
    multipart:
      max-file-size: 10GB   # 요청 파일 하나의 최대 크기
      max-request-size: 10GB  # 요청 파일 전체의 최대 크기

# MyBatis 매퍼(mapper) 파일 위치 설정
# src/main/resources 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:
  # 페이징 관련 세팅값
  pagination:
    write_pages: 10   # 한 [페이징] 당 몇개의 페이지가 표시되나?
    page_rows: 10   # 한 '페이지' 에 몇개의 글을 리스트 할것인지?

  # 파일 업로드 경로
  upload:
    path: upload








